In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
random_int_array = np.random.randint(1, 50, size=(1, 10))
random_int_array

array([[36, 44, 35, 37, 37, 37, 40, 42, 15, 38]], dtype=int32)

In [4]:
np.mean(random_int_array)

np.float64(36.1)

In [6]:
np.mean(random_int_array)

np.float64(36.1)

In [7]:
two_dim = np.array([[1, 2, 3], [4, 5, 6], [5, 6, 7]])

In [8]:
two_dim.shape

(3, 3)

In [11]:
tow= np.array([[[12,15,60],[45,75,89]],[[12,15,45],[45,78,95]]])

In [12]:
tow.shape

(2, 2, 3)

In [13]:
total_sum = np.sum(tow)

In [14]:
print(f"הסכום הכולל: {total_sum}")

הסכום הכולל: 586


In [15]:
random_int = np.random.randint(1, 100, size=(1, 20))
random_int

array([[18, 54, 63, 56, 14, 46, 59, 84, 68,  7, 32, 23, 23, 34, 63, 47,
        18, 44, 49, 21]], dtype=int32)

In [17]:
condition = random_int > 50
filtered_arr = random_int[condition]
filtered_arr

array([54, 63, 56, 59, 84, 68, 63], dtype=int32)

In [18]:
arr = np.arange(1, 11)

In [19]:
np.random.shuffle(arr)

In [20]:
selected_elements = arr[:4]